WIP: Integration SSH Portal config
uselagoon/lagoon-sync pull request #81
Opened 2022-11-08 16:44 UTC by timclifford

2022-11-17 16:00 UTC, bomoko reviewed
Looking good. Is there much else you need to add?

2022-11-17 16:00 UTC, bomoko commented on cmd/sync.go
> +		log.Println(fmt.Sprintf("ERROR: unable to generate token: %v", err))
Shouldn't this kill the process?

2022-11-17 16:00 UTC, bomoko commented on cmd/sync.go
> +func getServiceName(syncerType string) string {
This is going to change, or at least, will need to. The mongodb service isn't guaranteed to be there when there's dbaas :/
I'd leave them all as `cli` for the moment, and then make it possible to set the type as an argument either via the cli or the sync yml

2022-11-18 14:29 UTC, timclifford commented on cmd/sync.go
> +		log.Println(fmt.Sprintf("ERROR: unable to generate token: %v", err))
There is a general catch all on line 220, so thought this would be interesting to know where it failed.

2023-08-10 18:27 UTC, bomoko requested changes

2023-08-10 18:27 UTC, bomoko commented on cmd/sync.go
> +		utils.LogFatalError(errMessage, err.Error())
indeedy. Is this something you'll add?

2023-08-17 21:55 UTC, tobybellwood commented on cmd/sync.go
> +// Get SSH options based on the following prority:
once this PR (https://github.com/uselagoon/build-deploy-tool/pull/193) is merged, the ssh token (and API) details will be available in cluster as variables, and should be the priority.

2023-08-17 21:56 UTC, tobybellwood commented on cmd/sync.go
> +// 3. SSH defined fields in any config files (lagoon-sync.ssh, ssh)
`SSH defined fields` relate only to the token service, not SSH access

2023-08-23 10:58 UTC, tobybellwood commented on cmd/sync.go
> +			fmt.Print("\033[32mDo you want to define that now, or use the default ('https://api.lagoon.amazeeio.cloud/graphql')? (yes/no): \033[0m")
The `LAGOON_CONFIG_API_HOST` variable is available here, and should be used as a first preference?

2024-06-27 22:10 UTC, rocketeerbkw commented
I think this was done in https://github.com/uselagoon/lagoon-sync/pull/112

2024-06-27 22:10 UTC, closed without merging